server:
  port: 8160

spring:
  datasource:
    url: jdbc:mysql://47.96.126.125:3306/ding_cloud_push_refactor?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: liangzhi
    password: liangzhi
    driver-class-name: com.mysql.jdbc.Driver

snaker:
  file: flows/demoFlow.snaker
  flowName: leave